+ ./src/Allwmake
+ wmake libso ./thermophysicalModels/specie
'/home/weixian001/OpenFOAM/weixian001-2.3.0/platforms/linux64GccDPOpt/lib/libFPVFoamspecie.so' is up to date.
+ wmake libso ./thermophysicalModels/basic
Making dependency list for source file fluidThermo/fluidThermo.C
SOURCE=fluidThermo/fluidThermo.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/specie/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/reactionThermo/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/chemistryModel/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/fluidThermo.o
'/home/weixian001/OpenFOAM/weixian001-2.3.0/platforms/linux64GccDPOpt/lib/libFPVFoamfluidThermophysicalModels.so' is up to date.
+ wmake libso ./thermophysicalModels/reactionThermo
'/home/weixian001/OpenFOAM/weixian001-2.3.0/platforms/linux64GccDPOpt/lib/libFPVFoamreactionThermophysicalModels.so' is up to date.
+ wmake libso ./thermophysicalModels/chemistryModel
'/home/weixian001/OpenFOAM/weixian001-2.3.0/platforms/linux64GccDPOpt/lib/libFPVFoamchemistryModel.so' is up to date.
+ wmake libso ./turbulenceModels/compressible/turbulenceModel
Making dependency list for source file laminar/laminar.C
Making dependency list for source file turbulenceModel.C
SOURCE=turbulenceModel.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/specie/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/turbulenceModel.o
SOURCE=laminar/laminar.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/specie/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/laminar.o
'/home/weixian001/OpenFOAM/weixian001-2.3.0/platforms/linux64GccDPOpt/lib/libFPVFoamcompressibleTurbulenceModel.so' is up to date.
+ wmake libso ./turbulenceModels/compressible/RAS
Making dependency list for source file RASModel/RASModel.C
Making dependency list for source file derivedFvPatchFields/turbulentMixingLengthFrequencyInlet/turbulentMixingLengthFrequencyInletFvPatchScalarField.C
Making dependency list for source file derivedFvPatchFields/turbulentMixingLengthDissipationRateInlet/turbulentMixingLengthDissipationRateInletFvPatchScalarField.C
Making dependency list for source file derivedFvPatchFields/convectiveHeatTransfer/convectiveHeatTransferFvPatchScalarField.C
Making dependency list for source file derivedFvPatchFields/wallFunctions/v2WallFunctions/v2WallFunction/v2WallFunctionFvPatchScalarField.C
Making dependency list for source file derivedFvPatchFields/wallFunctions/kqRWallFunctions/kLowReWallFunction/kLowReWallFunctionFvPatchScalarField.C
Making dependency list for source file derivedFvPatchFields/wallFunctions/omegaWallFunctions/omegaWallFunction/omegaWallFunctionFvPatchScalarField.C
Making dependency list for source file derivedFvPatchFields/wallFunctions/fWallFunctions/fWallFunction/fWallFunctionFvPatchScalarField.C
Making dependency list for source file derivedFvPatchFields/wallFunctions/epsilonWallFunctions/epsilonLowReWallFunction/epsilonLowReWallFunctionFvPatchScalarField.C
Making dependency list for source file derivedFvPatchFields/wallFunctions/epsilonWallFunctions/epsilonWallFunction/epsilonWallFunctionFvPatchScalarField.C
Making dependency list for source file derivedFvPatchFields/wallFunctions/mutWallFunctions/mutLowReWallFunction/mutLowReWallFunctionFvPatchScalarField.C
Making dependency list for source file derivedFvPatchFields/wallFunctions/mutWallFunctions/mutUSpaldingWallFunction/mutUSpaldingWallFunctionFvPatchScalarField.C
Making dependency list for source file derivedFvPatchFields/wallFunctions/mutWallFunctions/mutURoughWallFunction/mutURoughWallFunctionFvPatchScalarField.C
Making dependency list for source file derivedFvPatchFields/wallFunctions/mutWallFunctions/mutUWallFunction/mutUWallFunctionFvPatchScalarField.C
Making dependency list for source file derivedFvPatchFields/wallFunctions/mutWallFunctions/mutkRoughWallFunction/mutkRoughWallFunctionFvPatchScalarField.C
Making dependency list for source file derivedFvPatchFields/wallFunctions/mutWallFunctions/mutkWallFunction/mutkWallFunctionFvPatchScalarField.C
Making dependency list for source file derivedFvPatchFields/wallFunctions/alphatWallFunctions/alphatJayatillekeWallFunction/alphatJayatillekeWallFunctionFvPatchScalarField.C
Making dependency list for source file v2f/v2f.C
Making dependency list for source file kOmegaSST/kOmegaSST.C
Making dependency list for source file SpalartAllmaras/SpalartAllmaras.C
Making dependency list for source file realizableKE/realizableKE.C
Making dependency list for source file LaunderGibsonRSTM/LaunderGibsonRSTM.C
Making dependency list for source file LRR/LRR.C
Making dependency list for source file LaunderSharmaKE/LaunderSharmaKE.C
Making dependency list for source file RNGkEpsilon/RNGkEpsilon.C
Making dependency list for source file kEpsilon/kEpsilon.C
Making dependency list for source file laminar/laminar.C
SOURCE=RASModel/RASModel.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/RASModel.o
SOURCE=laminar/laminar.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/laminar.o
SOURCE=kEpsilon/kEpsilon.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/kEpsilon.o
SOURCE=RNGkEpsilon/RNGkEpsilon.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/RNGkEpsilon.o
SOURCE=LaunderSharmaKE/LaunderSharmaKE.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/LaunderSharmaKE.o
SOURCE=LRR/LRR.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/LRR.o
SOURCE=LaunderGibsonRSTM/LaunderGibsonRSTM.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/LaunderGibsonRSTM.o
SOURCE=realizableKE/realizableKE.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/realizableKE.o
SOURCE=SpalartAllmaras/SpalartAllmaras.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/SpalartAllmaras.o
SOURCE=kOmegaSST/kOmegaSST.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/kOmegaSST.o
SOURCE=v2f/v2f.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/v2f.o
SOURCE=derivedFvPatchFields/wallFunctions/alphatWallFunctions/alphatJayatillekeWallFunction/alphatJayatillekeWallFunctionFvPatchScalarField.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/alphatJayatillekeWallFunctionFvPatchScalarField.o
SOURCE=derivedFvPatchFields/wallFunctions/mutWallFunctions/mutkWallFunction/mutkWallFunctionFvPatchScalarField.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/mutkWallFunctionFvPatchScalarField.o
SOURCE=derivedFvPatchFields/wallFunctions/mutWallFunctions/mutkRoughWallFunction/mutkRoughWallFunctionFvPatchScalarField.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/mutkRoughWallFunctionFvPatchScalarField.o
SOURCE=derivedFvPatchFields/wallFunctions/mutWallFunctions/mutUWallFunction/mutUWallFunctionFvPatchScalarField.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/mutUWallFunctionFvPatchScalarField.o
SOURCE=derivedFvPatchFields/wallFunctions/mutWallFunctions/mutURoughWallFunction/mutURoughWallFunctionFvPatchScalarField.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/mutURoughWallFunctionFvPatchScalarField.o
SOURCE=derivedFvPatchFields/wallFunctions/mutWallFunctions/mutUSpaldingWallFunction/mutUSpaldingWallFunctionFvPatchScalarField.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/mutUSpaldingWallFunctionFvPatchScalarField.o
SOURCE=derivedFvPatchFields/wallFunctions/mutWallFunctions/mutLowReWallFunction/mutLowReWallFunctionFvPatchScalarField.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/mutLowReWallFunctionFvPatchScalarField.o
SOURCE=derivedFvPatchFields/wallFunctions/epsilonWallFunctions/epsilonWallFunction/epsilonWallFunctionFvPatchScalarField.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/epsilonWallFunctionFvPatchScalarField.o
SOURCE=derivedFvPatchFields/wallFunctions/epsilonWallFunctions/epsilonLowReWallFunction/epsilonLowReWallFunctionFvPatchScalarField.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/epsilonLowReWallFunctionFvPatchScalarField.o
SOURCE=derivedFvPatchFields/wallFunctions/fWallFunctions/fWallFunction/fWallFunctionFvPatchScalarField.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/fWallFunctionFvPatchScalarField.o
SOURCE=derivedFvPatchFields/wallFunctions/omegaWallFunctions/omegaWallFunction/omegaWallFunctionFvPatchScalarField.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/omegaWallFunctionFvPatchScalarField.o
SOURCE=derivedFvPatchFields/wallFunctions/kqRWallFunctions/kLowReWallFunction/kLowReWallFunctionFvPatchScalarField.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/kLowReWallFunctionFvPatchScalarField.o
SOURCE=derivedFvPatchFields/wallFunctions/v2WallFunctions/v2WallFunction/v2WallFunctionFvPatchScalarField.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/v2WallFunctionFvPatchScalarField.o
SOURCE=derivedFvPatchFields/convectiveHeatTransfer/convectiveHeatTransferFvPatchScalarField.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/convectiveHeatTransferFvPatchScalarField.o
SOURCE=derivedFvPatchFields/turbulentMixingLengthDissipationRateInlet/turbulentMixingLengthDissipationRateInletFvPatchScalarField.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/turbulentMixingLengthDissipationRateInletFvPatchScalarField.o
SOURCE=derivedFvPatchFields/turbulentMixingLengthFrequencyInlet/turbulentMixingLengthFrequencyInletFvPatchScalarField.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/turbulentMixingLengthFrequencyInletFvPatchScalarField.o
'/home/weixian001/OpenFOAM/weixian001-2.3.0/platforms/linux64GccDPOpt/lib/libFPVFoamcompressibleRASModels.so' is up to date.
+ wmake libso ./turbulenceModels/compressible/LES
Making dependency list for source file LESModel/LESModel.C
Making dependency list for source file vanDriestDelta/vanDriestDelta.C
Making dependency list for source file SpalartAllmaras/SpalartAllmaras.C
Making dependency list for source file DeardorffDiffStress/DeardorffDiffStress.C
Making dependency list for source file homogeneousDynOneEqEddy/homogeneousDynOneEqEddy.C
Making dependency list for source file lowReOneEqEddy/lowReOneEqEddy.C
Making dependency list for source file oneEqEddy/oneEqEddy.C
Making dependency list for source file Smagorinsky/Smagorinsky.C
Making dependency list for source file GenSGSStress/GenSGSStress.C
Making dependency list for source file GenEddyVisc/GenEddyVisc.C
Making dependency list for source file DESModel/DESModel.C
SOURCE=LESModel/LESModel.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/turbulenceModels/LES/LESdeltas/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/turbulenceModels/LES/LESfilters/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/LESModel.o
In file included from LESModel/LESModel.C:31:
LESModel/LESModel.H: In member function ‘virtual Foam::tmp<Foam::GeometricField<double, Foam::fvPatchField, Foam::volMesh> > Foam::compressible::LESModel::DZt() const’:
LESModel/LESModel.H:254: error: no matching function for call to ‘grad(<unresolved overloaded function type>)’
LESModel/LESModel.H: In member function ‘virtual Foam::tmp<Foam::GeometricField<double, Foam::fvPatchField, Foam::volMesh> > Foam::compressible::LESModel::DZEff() const’:
LESModel/LESModel.H:263: error: no matching function for call to ‘grad(<unresolved overloaded function type>)’
LESModel/LESModel.C: In member function ‘virtual void Foam::compressible::LESModel::correctVarZ()’:
LESModel/LESModel.C:231: error: ‘rho_DZt’ was not declared in this scope
make: *** [Make/linux64GccDPOpt/LESModel.o] Error 1
+ wmake libso ./fvOptions
Making dependency list for source file sources/interRegion/interRegionHeatTransferModel/variableHeatTransfer/variableHeatTransfer.C
SOURCE=sources/interRegion/interRegionHeatTransferModel/variableHeatTransfer/variableHeatTransfer.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/sampling/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/thermophysicalModels/solidThermo/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/transportModels/compressible/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/specie/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/turbulenceModel/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/variableHeatTransfer.o
'/home/weixian001/OpenFOAM/weixian001-2.3.0/platforms/linux64GccDPOpt/lib/libFPVFoamfvOptions.so' is up to date.
+ wmake libso ./combustionModels
Making dependency list for source file YSLFModel/YSLFModels.C
Making dependency list for source file rhoCombustionModel/rhoChemistryCombustion/rhoChemistryCombustion.C
Making dependency list for source file rhoCombustionModel/rhoThermoCombustion/rhoThermoCombustion.C
Making dependency list for source file rhoCombustionModel/rhoCombustionModel/rhoCombustionModelNew.C
Making dependency list for source file rhoCombustionModel/rhoCombustionModel/rhoCombustionModel.C
Making dependency list for source file combustionModel/combustionModel.C
SOURCE=combustionModel/combustionModel.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/specie/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/reactionThermo/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/chemistryModel/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/turbulenceModel -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/ -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/turbulenceModels/LES/LESdeltas/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/turbulenceModels/LES/LESfilters/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/LES/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/combustionModel.o
SOURCE=rhoCombustionModel/rhoCombustionModel/rhoCombustionModel.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/specie/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/reactionThermo/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/chemistryModel/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/turbulenceModel -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/ -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/turbulenceModels/LES/LESdeltas/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/turbulenceModels/LES/LESfilters/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/LES/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/rhoCombustionModel.o
SOURCE=rhoCombustionModel/rhoCombustionModel/rhoCombustionModelNew.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/specie/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/reactionThermo/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/chemistryModel/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/turbulenceModel -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/ -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/turbulenceModels/LES/LESdeltas/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/turbulenceModels/LES/LESfilters/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/LES/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/rhoCombustionModelNew.o
SOURCE=rhoCombustionModel/rhoThermoCombustion/rhoThermoCombustion.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/specie/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/reactionThermo/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/chemistryModel/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/turbulenceModel -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/ -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/turbulenceModels/LES/LESdeltas/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/turbulenceModels/LES/LESfilters/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/LES/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/rhoThermoCombustion.o
SOURCE=rhoCombustionModel/rhoChemistryCombustion/rhoChemistryCombustion.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/specie/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/reactionThermo/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/chemistryModel/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/turbulenceModel -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/ -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/turbulenceModels/LES/LESdeltas/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/turbulenceModels/LES/LESfilters/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/LES/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/rhoChemistryCombustion.o
SOURCE=YSLFModel/YSLFModels.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/specie/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/reactionThermo/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/chemistryModel/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/turbulenceModel -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/ -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/turbulenceModels/LES/LESdeltas/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/turbulenceModels/LES/LESfilters/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/LES/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/YSLFModels.o
'/home/weixian001/OpenFOAM/weixian001-2.3.0/platforms/linux64GccDPOpt/lib/libFPVFoamCombustionModels.so' is up to date.
+ wmake ./applications/utilities/preProcessing/canteraToFPVFoam
Making dependency list for source file canteraToFPVFoam.C
SOURCE=canteraToFPVFoam.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/turbulenceModel/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/RAS/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/LES/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/turbulenceModels/LES/LESdeltas/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/specie/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/reactionThermo/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/chemistryModel/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/combustionModels/lnInclude -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/canteraToFPVFoam.o
g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/turbulenceModel/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/RAS/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/LES/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/turbulenceModels/LES/LESdeltas/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/specie/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/reactionThermo/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/chemistryModel/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/combustionModels/lnInclude -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -Xlinker --add-needed -Xlinker --no-as-needed Make/linux64GccDPOpt/Gamma.o Make/linux64GccDPOpt/canteraScanner.o Make/linux64GccDPOpt/canteraReader.o Make/linux64GccDPOpt/canteraToFPVFoam.o -L/usr/local/OpenFOAM//OpenFOAM-2.3.0/platforms/linux64GccDPOpt/lib \
	     -L/home/weixian001/OpenFOAM/weixian001-2.3.0/platforms/linux64GccDPOpt/lib -lODE -lFPVFoamspecie -lFPVFoamfluidThermophysicalModels -lFPVFoamspecie -lFPVFoamchemistryModel -lFPVFoamCombustionModels -lFPVFoamreactionThermophysicalModels -lFPVFoamcompressibleLESModels -lFPVFoamcompressibleTurbulenceModel -lFPVFoamcompressibleRASModels -lfiniteVolume -lmeshTools -lOpenFOAM -ldl   -lm -o /home/weixian001/OpenFOAM/weixian001-2.3.0/platforms/linux64GccDPOpt/bin/canteraToFPVFoam
+ wmake ./applications/utilities/postProcessing/FPVFoamPost
Making dependency list for source file FPVFoamPost.C
SOURCE=FPVFoamPost.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/turbulenceModel/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/RAS/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/LES/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/turbulenceModels/LES/LESdeltas/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/specie/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/reactionThermo/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/combustionModels/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/chemistryModel  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/FPVFoamPost.o
g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/turbulenceModel/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/RAS/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/LES/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/turbulenceModels/LES/LESdeltas/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/specie/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/reactionThermo/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/combustionModels/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/chemistryModel  -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -Xlinker --add-needed -Xlinker --no-as-needed Make/linux64GccDPOpt/FPVFoamPost.o -L/usr/local/OpenFOAM//OpenFOAM-2.3.0/platforms/linux64GccDPOpt/lib \
	     -L/home/weixian001/OpenFOAM/weixian001-2.3.0/platforms/linux64GccDPOpt/lib -lODE -lFPVFoamspecie -lFPVFoamfluidThermophysicalModels -lFPVFoamreactionThermophysicalModels -lFPVFoamCombustionModels -lFPVFoamchemistryModel -lFPVFoamcompressibleLESModels -lFPVFoamcompressibleTurbulenceModel -lFPVFoamcompressibleRASModels -lfiniteVolume -lmeshTools -lsampling -lOpenFOAM -ldl   -lm -o /home/weixian001/OpenFOAM/weixian001-2.3.0/platforms/linux64GccDPOpt/bin/FPVFoamPost
+ wmake ./applications/solver/FPVFoam
Making dependency list for source file FPVFoam.C
SOURCE=FPVFoam.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/turbulenceModel -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/specie/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/reactionThermo/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/fvOptions/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/sampling/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/chemistryModel -I/home/weixian001/OpenFOAM/FPVFoam/src/combustionModels/lnInclude -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/FPVFoam.o
/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude/readTimeControls.H: In function ‘int main(int, char**)’:
/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude/readTimeControls.H:38: warning: unused variable ‘maxDeltaT’
g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/weixian001/OpenFOAM/FPVFoam/src/turbulenceModels/compressible/turbulenceModel -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/specie/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/reactionThermo/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/basic/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/finiteVolume/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/fvOptions/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/meshTools/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/sampling/lnInclude -I/home/weixian001/OpenFOAM/FPVFoam/src/thermophysicalModels/chemistryModel -I/home/weixian001/OpenFOAM/FPVFoam/src/combustionModels/lnInclude -IlnInclude -I. -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OpenFOAM/lnInclude -I/usr/local/OpenFOAM//OpenFOAM-2.3.0/src/OSspecific/POSIX/lnInclude   -fPIC -Xlinker --add-needed -Xlinker --no-as-needed Make/linux64GccDPOpt/FPVFoam.o -L/usr/local/OpenFOAM//OpenFOAM-2.3.0/platforms/linux64GccDPOpt/lib \
	     -L/home/weixian001/OpenFOAM/weixian001-2.3.0/platforms/linux64GccDPOpt/lib -lFPVFoamcompressibleTurbulenceModel -lFPVFoamcompressibleLESModels -lFPVFoamcompressibleRASModels -lFPVFoamreactionThermophysicalModels -lFPVFoamspecie -lFPVFoamfluidThermophysicalModels -lFPVFoamchemistryModel -lfiniteVolume -lFPVFoamfvOptions -lmeshTools -lsampling -lFPVFoamCombustionModels -lOpenFOAM -ldl   -lm -o /home/weixian001/OpenFOAM/weixian001-2.3.0/platforms/linux64GccDPOpt/bin/FPVFoam
